#!/usr/bin/env bash
# script to install nginx and configure server on port 80
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
