#!/usr/bin/env bash
# script to install nginx and configure server on port 80
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
service nginx restart
