#!/usr/bin/env bash
# script to install nginx and redirect 'redirect_me'
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
touch /etc/nginx/html/error.html
echo "Ceci n'est pas une page" > /etc/nginx/html/error.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /error.html;
    location /error {
             root /etc/nginx/html;
             internal;
     }
}" > /etc/nginx/sites-available/default
service nginx restart
