#!/usr/bin/env bash
# install HAproxy and configure load balancer to server 1 & 2
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6  # enable ppa repo
sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bk
printf %s "
frontend traffic-in
   bind *:80
   mode http
   default_backend web-servers
   timeout client 30s

backend web-servers
    balance roundrobin
    mode http
    timeout connect 30s
    timeout server 30s
    server 206724-web-01 54.84.24.93:80 check
    server 206724-web-02 34.224.95.244:80 check
 " >  /etc/haproxy/haproxy.cfg
 sudo service haproxy restart
