#!/usr/bin/env bash
# runs a few pid operations
sudo touch /var/run/myscript.pid
echo "$$" | sudo tee /var/run/myscript.pid > /dev/null
trap "echo 'I hate the kill command' ; sudo rm /var/run/myscript.pid ; exit" SIGTERM
trap "echo 'Y U no love me?!' ; exit " SIGINT
trap "sudo rm /var/run/myscript.pid ; exit" SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
