#!/usr/bin/env bash
# prinf fizzbuzz (1 - 100)
i=1
while [ $i -le 100 ]
do
	if [ $((i%3)) = 0 ]
	then
		if [ $((i%5)) = 0 ]
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $((i%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$(( i + 1 ))
done
