#!/usr/bin/env bash
# displays content of /etc/passwd with IFS
file=/etc/passwd
while read -r line
do
	IFS=":"
	user=$(echo "$line" | cut -d ":" -f 1)
	grp=$(echo "$line" | cut -d ":" -f 4)
	home=$(echo "$line" | cut -d ":" -f 6)
	cmd=$(echo "$line" | cut -d ":" -f 7)
	pass=$(echo "$line" | cut -d ":" -f 2)
	info=$(echo "$line" | cut -d ":" -f 5)
	echo "The user $user is part of the $grp gang, lives in the $home and rides $cmd. USER ID's place is protected by the passcode $pass, more info about the user here: $info"
done < $file
