#!/usr/bin/env bash
# displays content of /etc/passwd with IFS
file=/etc/passwd
IFS=":"
while read -r username pass uid gid info home shell
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < $file
