#!/usr/bin/env bash
# prints bad luck - 4th it, good luck - 8th it
i=1
while [ $i -le 10 ] 
do
	if [ $i = 4 ]
	then
		echo "good luck"
	elif [ $i = 8 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
