#!/usr/bin/env bash
# Displays time: hrs minutes
min=0
hour=0
while [ $hour -lt 12 ]
do
	if [ $min = 0 ]
	then
		echo "Hour: $hour"
	elif [ $min = 60 ]
	then
		hour=$(( hour + 1 ))
		echo "Hour: $hour"
		min=0
	else
		echo "$min"
	fi
	min=$(( min + 1 ))
done
