#!/usr/bin/env bash
# Displays time: hrs minutes
min=0
hour=0
while [ $hour -le 12 ]
do
	if [ $min = 0 ]
	then
		echo "Hour: $hour"
	elif [ $min = 60 ]
	then
		if [ $hour = 12 ]
		then
				break
		else
			hour=$(( hour + 1 ))
			echo "Hour: $hour"
			min=0
		fi
	else
		echo "$min"
	fi
	min=$(( min + 1 ))
done
