#!/usr/bin/env bash
# bash command to get nginx running as non-root user
sudo apt-get install -y lsof
sudo lsof -ti :8080 | xargs kill
# /etc/nginx/nginx.conf  -> user nginx;
sudo sed -i '/^user/c\user nginx;' /etc/nginx/nginx.conf
# /etc/nginx/sites-enabled/default -> listen:8080 
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sudo chown nginx:nginx /var/log/nginx/error.log
sudo chown nginx:nginx /var/log/nginx/access.log
# sudo chown nginx:nginx /var/run/nginx.pid
nginx -c /etc/nginx/nginx.conf
