#!/usr/bin/env bash
# run nginx as non-root shorter version
sudo lsof -ti :8080 | xargs kill
sudo sed -i '/^user/c\user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sudo chown nginx:nginx /var/log/nginx/error.log /var/log/nginx/access.log
nginx -c /etc/nginx/nginx.conf
